//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public string ClientName { get; set; }
        public string CarModel { get; set; }
        public int BrokenPartID { get; set; }
        public Nullable<int> InstalledPartID { get; set; }
        public string Status { get; set; }
        public decimal RepairPrice { get; set; }
        public decimal FinePrice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual Parts Parts1 { get; set; }
        public virtual Players Players { get; set; }
    }
}
