//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrders
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int DeliveryAfter { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual Players Players { get; set; }
    }
}
