//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPShootAndBunny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public decimal DiscountPercent { get; set; }
        public bool IsFrozen { get; set; }
        public decimal AverageRating { get; set; }
        public int ProductTypeId { get; set; }
        public int ManufacturerId { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
